export enum ErrorTypes {
  NoDoc = 'NoDoc',
  UpdateFail = 'UpdateFail',
  SetFail = 'SetFail',
  DeleteFail = 'DeleteFail',
  Impossible = 'Impossible',
  Unknown = 'Unknown',
  Unauthorized = 'Unauthorized',
  Forbidden = 'Forbidden',
  NotFound = 'NotFound',
  Conflict = 'Conflict',
  Validation = 'Validation',
  InternalServerError = 'InternalServerError',
  ServiceUnavailable = 'ServiceUnavailable',
  RateLimit = 'RateLimit',
  Empty = 'Empty',
  Fail = 'Fail',
  Die = 'Die',
  Interrupt = 'Interrupt',
  Sequential = 'Sequential',
  Parallel = 'Parallel',
}
