/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "CLERK_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLERK_WEBHOOK_SIGNING_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TEMPORAL_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "pgdb-primary-us-east-1a": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "pgdb-replica-af-south-1": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "pgdb-replica-eu-west-3": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "pgdb-replica-us-east-1c": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "steeple-works": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "valkey-us-east-1": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "vpc-af-south-1": {
      "type": "sst.aws.Vpc"
    }
    "vpc-eu-west": {
      "type": "sst.aws.Vpc"
    }
    "vpc-us-east-1": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
  }
}
